クエストドメインの実装
hal-tokyo-cello/cello-core pull request #21
Opened 2022-06-28 09:09 UTC by reone19

4択問題、組み合わせ問題の作成が早めに完了いたしました。レビューお願いします。

2022-06-28 09:46 UTC, CornerSyrup requested changes
組み合わせ問題の回答関数以外は任意修正

2022-07-10 21:05 UTC, KleinChiu reviewed
LGTM
@reone19 もう一回見る？大丈夫だったらマージお願い

2022-07-10 21:07 UTC, KleinChiu approved these changes

2022-07-10 21:09 UTC, reone19 commented
コミット内容と、更新ファイルの内容を確認します

2022-07-10 21:13 UTC, reone19 commented
LGTM

2022-07-10 21:13 UTC, merged